### ISSUE TITLE
Highlighting lines doesn't select full line

### ISSUE THREAD

**Issue by Benjaminwfox** [talmand/Brackets-Select-Lines#4]
Hey, thanks for making this plugin! It was the first thing I installed when I started using brackets. I was getting annoyed though, because when highlighting lines the highlight would end and the end of the code (rather than grabbing the full line to the start of the next line). This made copy-pasting lines a pain, the formatting wouldn't behave like I expected coming from other editors. I made a minor change to the code which I think provides behavior consistent with other editors. Now it selects the 0 character at the first line AFTER the end of the selection, allowing for easy copy-pasting of full lines. Also I'm not very good at github, so I'll just leave the code here for you to include if you think it makes sense.

Thanks! Ben

        var lineSelecting = function (e) {
            var newLine = instance.lineAtHeight(e.pageY);
            newLine += 1;
            
            if (!event.ctrlKey) {
                instance.setSelection(
                    {line: startLine, ch: 0}, //startLine < newLine ? 0 : null},
                    {line: newLine, ch: 0} //startLine < newLine ? null : 0}
                );
            } else {
                instance.addSelection(
                    {line: startLine, ch: 0}, //startLine < newLine ? 0 : null},
                    {line: newLine, ch: 0} //startLine < newLine ? null : 0}
                );
            }
        };

**Comment by talmand** [comment]
Finally remembered to update the registry with this new code. Thanks.
