### ISSUE TITLE
Selecting a Line moves window to the right.

### ISSUE THREAD

**Issue by jeremybriley** [talmand/Brackets-Select-Lines#6]
First, Thank you! this is great functionality!

Small issue, but annoying:
When you select a line number on the left, the window on the right might move over when you have a long code line, no wrap on, and vertical split.

See screen print for mark up.  http://postimg.org/image/9qp9hd9n5/

It would be nice to not move the horizontal orientation of the screen. Just leave it flush left when you select a single or multiple lines.

Thank you again!

**Comment by talmand** [comment]
So far I've been unable to reproduce this.

With two documents open in vertical split, no word wrap, the selection behaves as I would expect.

Can you tell me what version of Brackets you are running plus what OS is on your computer?

**Comment by jeremybriley** [comment]
wow, thanks for looking into.

Brackets:
Release 1.1 build 1.1.0-15558 (release ea908cae5) 
build timestamp: Wed Dec 17 2014 12:51:02 GMT-0800

Win 7 - ultimate

**Comment by talmand** [comment]
Well, crap, that's what I'm running here.

Is it always the same files or can you consistently reproduce with other files?

What does it do for you if you turn on word wrap?

**Comment by jeremybriley** [comment]
It does not happen with word wrap on (because the lines are within the same window). 

It's not file dependent, happens with all files that have lines of code that go outside the initial view(window)

**Comment by talmand** [comment]
Well. That's just a bummer. I'll have to make a note to try several different files to see if I can get something that behaves the same.

Which, I literally just updated this extension with new code. It's probably not related but I'm curious if updating would automagically fix this in some strange, convenient way.

I doubt it, but you never know.

Can you give me a list of the other extensions you have installed? Maybe one of them is causing a conflict of some sort.

**Comment by poggije** [comment]
there is an error while i'm installing it.
Installation Failed
Unknown internal error
How can i Fix it???

**Comment by talmand** [comment]
@poggije - please open a new issue with your error. Be sure to include details such as what Brackets version, which OS, and how you are attempting to install the extension.

Thanks.
