### ISSUE TITLE
When in split screen mousing over unfocused file's gutter selects text in focused file

### ISSUE THREAD

**Issue by Christianjuth** [talmand/Brackets-Select-Lines#7]
When using brackets split screen feature you must first highlight the screen then select the line.
Mousing over the unfocused file's gutter selects text in focused file. For example: If I select the right file then drag my cursor on the left files gutter it selects text in the right file.

**Comment by talmand** [comment]
Ok, I can reproduce this.

I'll see what I can figure out.

Thanks for the bug report.

**Comment by talmand** [comment]
@Christianjuth I committed changes last night that should fix this. Would it be possible for you to download the zip file and install manually to test it for me? I'm trying to avoid a "it works on my machine" situation.

Right now the highlighting and selecting should only work when the pane has focus.
