### ISSUE TITLE
Highlight line numbers on selection

### ISSUE THREAD

**Issue by adamdehaven** [talmand/Brackets-Select-Lines#9]
By default, when the users's cursor is on a line, that line number is highlighted. 

Default Brackets behavior (notice the white '30' line number
![default](https://cloud.githubusercontent.com/assets/2229946/24772592/ea8b097a-1adf-11e7-9cf2-f9b32599abee.png)

It would be nice if selecting the entire line (via this extension) also highlighted the line numbers that are selected.

Current extension behavior (notice the line numbers are *not* highlighted)
![extension](https://cloud.githubusercontent.com/assets/2229946/24772593/ea8cb13a-1adf-11e7-8b6f-ef4c15cdbadc.png)

**Comment by talmand** [comment]
Unfortunately I've not done much Brackets work lately so I'm not sure when or if I would get to this.

But, this is a good idea. I'll try to take a look at it when I have time or the need to do a small project outside my current scope of duties.

Thanks for the feedback.

**Comment by adamdehaven** [comment]
No worries. It was just a suggestion. I may code it myself and submit a pull request if that's easier :)

**Comment by talmand** [comment]
Feel free, I'm always open to pull requests. I can't promise a timely turnaround to get it updated in the extensions download but I'll get it in there as fast as I can.
